name: pyemu
channels:
  - conda-forge
  - nodefaults
dependencies:
  # required
  - python>=3.9
  - libopenblas < 0.3.30
  - numpy
  - pandas
  # optional
  - matplotlib
  - pyshp
  - jinja2
  # tests
  - coveralls
  - flaky
  - pytest
  - pytest-cov
  - pytest-xdist
  - nbmake
  - shapely
  - pyproj
  - flopy
  - modflow-devtools
  - scikit-learn
  - pip
  - ffmpeg
  - jupyter
  - jupytext
  - jupyterlab
