name: Deploy Quarto Site
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up mamba environment (includes Quarto)
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-downloads: true
          init-shell: bash

      - name: Make executables accessible
        run: |
          chmod +x bin/linux/*

      - name: Render site in environment
        run: |
          export PATH="$PWD/bin/linux:$PATH"
          micromamba run -n madison quarto render
        
      - name: Add .nojekyll
        run: |
          touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
