name: Deploy Quarto Site
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up mamba environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-downloads: true
          init-shell: bash

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Make executables accessible
        run: |
          chmod +x bin/linux/*

      - name: Setup Python kernel
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate madison
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: Render site (in conda env)
        run: |
          export PATH="$PWD/bin/linux:$PATH"
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate madison
          quarto render

      - name: Add .nojekyll
        run: |
          touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
