name: Deploy Quarto Site
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up mamba environment (includes Quarto)
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-downloads: true
          init-shell: bash

      - name: Make executables accessible
        run: |
          chmod +x bin/linux/*

      - name: Render site in environment
        run: |
          export PATH="$PWD/bin/linux:$PATH"
          # Install kernel in the environment
          micromamba run -n madison python -m ipykernel install --name python3 --display-name "Python 3"
          # Execute notebooks using Jupyter directly (this should work since Jupyter is in the same env)
          micromamba run -n madison jupyter nbconvert --to notebook --execute --inplace notebooks/simple_pstfrom.ipynb
          micromamba run -n madison jupyter nbconvert --to notebook --execute --inplace notebooks/simple_ies.ipynb  
          micromamba run -n madison jupyter nbconvert --to notebook --execute --inplace notebooks/simple_LP_example.ipynb
          # Now render with Quarto (execution disabled since notebooks are pre-executed)
          micromamba run -n madison quarto render --execute=false
        
      - name: Add .nojekyll
        run: |
          touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
