name: Deploy Quarto Site
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up mamba environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-downloads: true
          init-shell: bash

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Make executables accessible
        run: |
          chmod +x bin/linux/*
          export PATH="$PWD/bin/linux:$PATH"
          echo "PATH=$PWD/bin/linux:$PATH" >> $GITHUB_ENV

      - name: Setup Python kernel and environment
        run: |
          micromamba activate madison
          python -m ipykernel install --user --name python3 --display-name "Python 3"
          echo "JUPYTER_PATH=$(micromamba run -n madison python -c 'import jupyter; print(jupyter.path.jupyter_path()[0])')" >> $GITHUB_ENV

      - name: Render site (in conda env)
        run: |
          micromamba activate madison
          export PATH="$PWD/bin/linux:$PATH"
          quarto render

      - name: Add .nojekyll
        run: |
          touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
